### ISSUE TITLE
Verbose Listing

### ISSUE THREAD

**Issue by uthiel** [ripeda/Lectricus#2]
Would it be possible to list all Electron apps instead of just the vulnerable ones?

**Comment by khronokernel** [comment]
Hi, does it not already list all Electron applications? They're categorized as "Correctly Configured Electron Fuses" in the GUI and CLI.

<img width="500" alt="Lectricus - GUI - List applications" src="https://github.com/ripeda/Lectricus/assets/48863253/35645d7c-9754-4ebb-af84-d989d5ff334c">

I should mention there's a library I wrote that Lectricus uses, `electron-search` that you might be able to use for this purpose:
* https://github.com/ripeda/electron-search

Is there a specific workflow you're thinking of using Lectricus with?

**Comment by uthiel** [comment]
Apparently I only have vulnerable apps 🙁 

I can see from the screenshot though that Lectricus does have the requested feature already built in, so I'm closing this Issue. Thanks for your work and the quick response 👍

Regarding the workflow: getting rid of all Electron apps 😉
